[package]
name = "gn-shield-sensors-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gn-shield-sensors-common = { path = "../gn-shield-sensors-common" }
gn-shield-config = { path = "../gn-shield-config" }
notify = { workspace = true }
aya = "0.13"
ipnet = "2.12"

[dev-dependencies]
tempfile = "3"
