//! Honeypot and canary file management.
//! Provides deployment and tamper detection for decoy files to catch ransomware immediately.

use std::collections::HashSet;
use std::fs::File;
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};

pub const CANARY_TOKEN: &[u8] = b"--- GN-SHIELD-CANARY-TOKEN-v1-DO-NOT-MODIFY ---";
pub const CANARY_FILENAMES: &[&str] = &[
    ".gn_canary_report.docx",
    ".gn_canary_finance.xlsx",
    ".gn_canary_passwords.txt",
];

#[derive(Debug, Default, Clone)]
pub struct HoneypotManager {
    deployed_canaries: HashSet<PathBuf>,
}

impl HoneypotManager {
    #[must_use]
    pub fn new() -> Self {
        Self {
            deployed_canaries: HashSet::new(),
        }
    }

    /// Generates standard canary payload containing the canary token and plaintext data.
    #[must_use]
    pub fn generate_canary_payload(label: &str) -> Vec<u8> {
        let mut payload = Vec::new();
        payload.extend_from_slice(CANARY_TOKEN);
        payload.extend_from_slice(b"\nCONFIDENTIAL INTERNAL FILE\nLabel: ");
        payload.extend_from_slice(label.as_bytes());
        payload.extend_from_slice(b"\nGenerated by GN-Shield Decoy Engine.\n");
        payload
    }

    /// Deploys honeypot files in the target directory and registers them.
    pub fn deploy_in_dir(&mut self, dir: &Path) -> io::Result<Vec<PathBuf>> {
        let mut deployed = Vec::new();
        for &filename in CANARY_FILENAMES {
            let path = dir.join(filename);
            let payload = Self::generate_canary_payload(filename);
            let mut file = File::create(&path)?;
            file.write_all(&payload)?;
            self.deployed_canaries.insert(path.clone());
            deployed.push(path);
        }
        Ok(deployed)
    }

    /// Registers a custom canary path.
    pub fn register_canary(&mut self, path: PathBuf) {
        self.deployed_canaries.insert(path);
    }

    /// Checks if a given path corresponds to a known honeypot/canary file.
    #[must_use]
    pub fn is_canary(&self, path: &Path) -> bool {
        if self.deployed_canaries.contains(path) {
            return true;
        }

        // Check file name matching convention
        if let Some(file_name) = path.file_name().and_then(|f| f.to_str()) {
            CANARY_FILENAMES.contains(&file_name) || file_name.starts_with(".gn_canary_")
        } else {
            false
        }
    }

    /// Checks if the canary file at path has been tampered with (modified, encrypted, or deleted).
    /// Returns true if tampered (e.g. file missing, or canary token missing / encrypted).
    pub fn is_tampered(&self, path: &Path) -> bool {
        if !path.exists() {
            // Deleted or moved by ransomware
            return true;
        }

        match File::open(path) {
            Ok(mut file) => {
                let mut buffer = Vec::new();
                if file.read_to_end(&mut buffer).is_err() {
                    return true;
                }
                // If the token was altered or encrypted, it will not be present
                !buffer
                    .windows(CANARY_TOKEN.len())
                    .any(|w| w == CANARY_TOKEN)
            }
            Err(_) => true,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_deploy_and_verify_clean_canaries() {
        let temp = tempdir().expect("tempdir failed");
        let mut manager = HoneypotManager::new();

        let deployed = manager.deploy_in_dir(temp.path()).expect("deploy failed");
        assert_eq!(deployed.len(), CANARY_FILENAMES.len());

        for path in &deployed {
            assert!(manager.is_canary(path));
            assert!(!manager.is_tampered(path), "Untampered canary flagged!");
        }
    }

    #[test]
    fn test_canary_tampered_by_encryption_or_overwrite() {
        let temp = tempdir().expect("tempdir failed");
        let mut manager = HoneypotManager::new();
        let deployed = manager.deploy_in_dir(temp.path()).expect("deploy failed");

        let target = &deployed[0];

        // Simulate ransomware encrypting the file with random bytes
        let encrypted_bytes = vec![0xAB; 500];
        fs::write(target, encrypted_bytes).expect("overwrite failed");

        assert!(manager.is_canary(target));
        assert!(
            manager.is_tampered(target),
            "Tampered canary was not detected!"
        );
    }

    #[test]
    fn test_canary_tampered_by_deletion() {
        let temp = tempdir().expect("tempdir failed");
        let mut manager = HoneypotManager::new();
        let deployed = manager.deploy_in_dir(temp.path()).expect("deploy failed");

        let target = &deployed[1];
        fs::remove_file(target).expect("remove failed");

        assert!(manager.is_canary(target));
        assert!(
            manager.is_tampered(target),
            "Deleted canary was not detected!"
        );
    }
}
